YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Models/Fans/FanButtonModel.cs
namespace Clicks.Yoga.Portal.Models.Fans
{
    public class FanButtonModel
    {
        public FanButtonModel(int entityId, string entityTypeName, bool isFanned, bool canFan  )
        {
            EntityId = entityId;
            EntityTypeName = entityTypeName;
            IsFanned = isFanned;
            CanFan = canFan;
        }

        public int EntityId { get; set; }

        public string EntityTypeName { get; set; }

        public bool IsFanned { get; set; }

        public bool CanFan { get; set; }

        public bool NewsFeed { get; set; }

        public int FanCount { get; set; }
    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Models/Fans/FanConfirmationModel.cs
using Clicks.Yoga.Domain.Entities;

namespace Clicks.Yoga.Portal.Models.Fans
{
    public class FanConfirmationModel
    {
        public FanConfirmationModel(IEntityHandle entity)
        {
            if (entity != null) EntityName = entity.Name;
        }

        public string EntityName { get; set; }
    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Models/Galleries/GalleryUpdateEntryModel.cs
namespace Clicks.Yoga.Portal.Models.Galleries
{
    public class GalleryUpdateEntryModel
    {
        public int EntryId { get; set; }

        public string Name { get; set; }

        public bool? IsCover { get; set; }

        public bool? IsPromoted { get; set; }
    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Clicks.Yoga.Context;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Domain.Services;
using Clicks.Yoga.Portal.Models.Search;
using Microsoft.Data.OData;
using Clicks.Yoga.Portal.Models.Community;
using System;
using Clicks.Yoga.Geography;
using System.Configuration;
using System.Text.RegularExpressions;

namespace Clicks.Yoga.Portal.Controllers
{
    public class SearchController : YogaController
    {
        public SearchController(
            IWorkUnit workUnit,
            ISecurityContext securityContext,
            IEntityService entityService,
            ISearchService searchService,
            IAccreditationBodyService accreditationBodyService,
            IPoseService poseService,
            IStyleService styleService,
            ITeacherTrainingService teacherTrainingService,
            ITeacherService teachers,
            IVenueService venues,
            IProfileService profileService,
            IActivityService activityService,
            IStyleOrganisationService styleOrganisationService,
             IGroupService groupService
            )
            : base(workUnit, securityContext)
        {
            EntityService = entityService;
            SearchService = searchService;
            TeacherService = teachers;
            VenueService = venues;
            AccreditationBodyService = accreditationBodyService;
            PoseService = poseService;
            StyleService = styleService;
            TeacherTrainingService = teacherTrainingService;
            ProfileService = profileService;
            ActivityService = activityService;
            StyleOrganisationService = styleOrganisationService;
            GroupService = groupService;
        }

        private IStyleOrganisationService StyleOrganisationService { get; set; }

        private IActivityService ActivityService { get; set; }

        private IEntityService EntityService { get; set; }

        private ISearchService SearchService { get; set; }

        private IAccreditationBodyService AccreditationBodyService { get; set; }

        private IPoseService PoseService { get; set; }

        private IStyleService StyleService { get; set; }

        private ITeacherTrainingService TeacherTrainingService { get; set; }

        private ITeacherService TeacherService { get; set; }

        private IVenueService VenueService { get; set; }

        private IProfileService ProfileService { get; set; }

        private IGroupService GroupService { get; set; }

        public ActionResult AutocompleteTeachers(string name, bool? owned)
        {
            if (string.IsNullOrEmpty(name) || name.Length < 3) return Json(new List<object>());

            var type = EntityService.GetEntityType("Teacher");

            var criteria = new SearchCriteria
            {
                EntityTypeIds = new[] { type.Id },
                Keywords = name,
                Owned = owned,
                Stubbed = null
            };

            SearchService.PrepareCriteria(criteria);

            var results = SearchService.Search(criteria).Results;
            var bits = results.Select(r => new { Id = r.EntityId, r.Name });

            return Json(bits, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AutocompleteVenues(string name, bool? owned)
        {
            if (string.IsNullOrEmpty(name) || name.Length < 3) return Json(new List<object>());

            var type = EntityService.GetEntityType("Venue");

            var criteria = new SearchCriteria
            {
                EntityTypeIds = new[] { type.Id },
                Keywords = name,
                Owned = owned,
                Stubbed = null
            };

            SearchService.PrepareCriteria(criteria);

            var results = SearchService.Search(criteria).Results;
            var bits = results.Select(r => new { Id = r.EntityId, r.Name });

            return Json(bits, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index(SearchCriteriaModel criteria)
        {
            return RedirectToAction("Discover");
        }

        public ActionResult Results(SearchCriteriaModel model)
        {
            PopulateDefaultLocation(model);

            model.PageIndex = 0;
            model.PageSize = 1000;

            return View(new SearchResultsModel(model, Search(model)));
        }

        public ActionResult Discover()
        {
            return View(new SearchDiscoverModel(
                            AccreditationBodyService.LuckyDip(),
                            TeacherTrainingService.LuckyDip(),
                            TeacherService.LucyDip(),
                            VenueService.LuckyDip(),
                            StyleOrganisationService.LuckyDip(),
                            ActivityService.LuckyDip()));
        }

        public ActionResult Profiles(SearchCriteriaModel model)
        {
            PopulateDefaultLocation(model);

            model.Types = "Profile";
            return View(new SearchProfilesModel(model, Search(model)));
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult ProfilesNavigation()
        {
            return View();
        }

        public ActionResult Teachers(SearchCriteriaModel model)
        {
            PopulateDefaultLocation(model);

            model.Types = "Teacher";

            return View(new SearchTeachersModel(model, Search(model)));
        }

        public ActionResult TeachersMap(SearchCriteriaModel model)
        {
            //DW - Commented out for DYC-44 to avoid entering default
            //PopulateDefaultLocation(model);

            model.Types = "Teacher";
            model.PageSize = null;
            SetSearchCriteria(model);
            model.Stubbed = false;
            return View(new SearchTeachersModel(model));
        }

        [HttpPost]
        public ActionResult TeachersJson(SearchCriteriaModel model)
        {
            model.Types = "Teacher";
            model.PageSize = 1000;
            SetSearchCriteria(model);
            //var searchDistance = decimal.Parse(ConfigurationManager.AppSettings["Clicks.Yoga.Search.Distance"]);
            var results = new List<SearchResultModel>();

            foreach (var result in Search(model).Results)
            {
                //var inRadius = InRadius(model.Longitude.Value, model.Latitude.Value, result.LocationGeography.Longitude.Value, result.LocationGeography.Latitude.Value, searchDistance);
                if (model.Location != null)
                {
                    char[] delimiters = new[] { ',', ' ' };  // List of your delimiters

                    List<String> resultArray = new List<string>();

                    if (result.City != null)
                    {
                        resultArray = result.City.ToLower().Split(delimiters, StringSplitOptions.RemoveEmptyEntries).ToList();
                    }

                    if (result.Country != null)
                    {
                        foreach (var countryItem in result.Country.ToLower().Split(delimiters, StringSplitOptions.RemoveEmptyEntries).ToList())
                        {
                            resultArray.Add(countryItem);
                        }
                    }

                    var searchArray = model.Location.ToLower().Split(delimiters, StringSplitOptions.RemoveEmptyEntries).ToList();

                    searchArray = CheckCommonAbbr(searchArray, model.Location.ToLower());

                    var matches = resultArray.Intersect(searchArray);

                    if (matches.Any())
                    {
                        results.Add(new SearchResultModel(result));
                    }
                }
                else
                {
                    results.Add(new SearchResultModel(result));
                }

            }

            bool empty = results.Count == 0;

            return Json(new { results, empty });
        }

        private List<string> CheckCommonAbbr(List<string> searchArray, string location)
        {
            if (location.Contains("united kingdom"))
            {
                searchArray.Add("uk");
            }
            if (location.Contains("uk"))
            {
                searchArray.Add("united");
                searchArray.Add("kingdom");
            }
            if (location.Contains("united states"))
            {
                searchArray.Add("usa");
            }
            if (location.Contains("usa"))
            {
                searchArray.Add("united");
                searchArray.Add("states");
            }

            return searchArray;
        }

        public bool InRadius(double criteria_x, double criteria_y, double result_x, double result_y, decimal searchDistance)
        {
            var distance = DistanceAlgorithm.DistanceBetweenPlaces(criteria_x, criteria_y, result_x, result_y);
            return distance <= double.Parse(searchDistance.ToString());
        }

        [HttpPost]
        public ActionResult TeacherInformation(int entityId)
        {
            var venue = TeacherService.GetTeacher(entityId);
            return PartialView(new SearchTeacherInformationModel(venue));
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult TeachersNavigation(string action = "Teachers")
        {
            var criteria = GetSearchCriteria();
            var model = new SearchTeachersNavigationModel(action, criteria, TeacherService.GetTeacherServices(), StyleService.GetStyles(), AccreditationBodyService.GetAccreditationBodies());
            return View(model);
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult GroupsNavigation(string keywords)
        {

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Controllers/StylesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Clicks.Yoga.Context;
using Clicks.Yoga.Domain;
using Clicks.Yoga.Domain.Services;
using Clicks.Yoga.Portal.Models.Styles;
using Clicks.Yoga.Web;
using System.Configuration;
using System.Web.UI;

namespace Clicks.Yoga.Portal.Controllers
{
    public class StylesController : YogaController
    {
        public StylesController(
            IWorkUnit workUnit,
            ISecurityContext securityContext,
            IStyleService styleService
        ) : base(workUnit, securityContext)
        {
            StyleService = styleService;
        }

        private IStyleService StyleService { get; set; }
        
        public ActionResult Navigation()
        {
            var type = Session["Styles.Navigation"] ?? StyleNavigationType.Directory;

            switch ((StyleNavigationType)type)
            {
                case StyleNavigationType.Directory:
                    return TraitsNavigation();
                case StyleNavigationType.Traits:
                    return TraitsNavigation();
                default:
                    return new EmptyResult();
            }
        }
        
        public ActionResult DirectoryNavigation()
        {
            return View("DirectoryNavigation", new StyleDirectoryNavigationModel(StyleService.GetStyles()));
        }
        
        public ActionResult TraitsNavigation()
        {
            var traitIds = (Session["Styles.Traits"] as List<int>) ?? new List<int>();
            var traits = StyleService.GetTraits();
            var styles = traitIds.Count > 0 ? StyleService.GetStylesByTraits(traitIds) : StyleService.GetStyles();
            var groups = traits.Select(e => e.Group).Distinct();

            return View("TraitsNavigation", new StyleTraitsNavigationModel(groups, styles, traitIds));
        }

     
        public ActionResult Display(int id)
        {
            var styles = StyleService.GetStyles();
            var style = styles.Where(e => e.Id == id).FirstOrDefault();

            if (style == null) throw new UnknownEntityException();

            foreach (var result in EnsureUrlSlug(style)) return result;

            return View(new StyleDisplayModel(style, styles));
        }

        public ActionResult Directory()
        {
            Response.Redirect("/");


            Session["Styles.Navigation"] = StyleNavigationType.Directory;
            Session["Styles.Last"] = Request.Url.ToString();

            return View();
        }

        public ActionResult DirectoryPartial(int skip = 0, int take = -1)
        {
            Session["Styles.Navigation"] = StyleNavigationType.Directory;
            Session["Styles.Last"] = Request.Url.ToString();

            if (take == -1) take = int.Parse(ConfigurationManager.AppSettings["Clicks.Yoga.InfiniteScroll.DefaultNumberOfStyles"]);
            
            return View(new StyleIndexModel(StyleService.GetStylesForInfiniteScroll(skip, take)));
        }


        public ActionResult Index(string traitIdString, string traitNameString)
        {
            var traitIds = WebUtility.SplitUrlSlug<int>(traitIdString);
            
            Session["Styles.Navigation"] = StyleNavigationType.Traits;
            Session["Styles.Traits"] = traitIds;
            Session["Styles.Last"] = Request.Url.ToString();

            return View(new StyleTraitsIndexModel(traitIdString, traitNameString));
        }

        public ActionResult StylesPartial(string traitIdString, string traitNameString, int skip = 0, int take = -1)
        {
            if (take == -1) take = int.Parse(ConfigurationManager.AppSettings["Clicks.Yoga.InfiniteScroll.DefaultNumberOfStyles"]);
            var traitIds = WebUtility.SplitUrlSlug<int>(traitIdString);
            var styles = traitIds.Count > 0 ? StyleService.GetStylesByTraitsForInfiniteScroll(traitIds, skip, take) : StyleService.GetStylesForInfiniteScroll(skip, take);
            var model = new StyleTraitsModel(styles, traitIdString, traitNameString);

            return View(model);
        }

        public ActionResult SelectTrait(string traitIdString, string traitNameString, int traitId)
        {
            var traitIds = WebUtility.SplitUrlSlug<int>(traitIdString);
            var traitNames = WebUtility.SplitUrlSlug<string>(traitNameString);

            var trait = StyleService.GetTrait(traitId);

            traitIds.Add(traitId);
            traitNames.Add(WebUtility.UrlSlug(trait.Name));

            Session["Styles.Last"] = Request.Url.ToString();

            return RedirectToTraits(traitIds, traitNames);
        }

        public ActionResult UnselectTrait(string traitIdString, string traitNameString, int traitId)
        {
            var traitIds = WebUtility.SplitUrlSlug<int>(traitIdString);
            var traitNames = WebUtility.SplitUrlSlug<string>(traitNameString);

            var trait = StyleService.GetTrait(traitId);

            traitIds.Remove(traitId);
            traitNames.Remove(WebUtility.UrlSlug(trait.Name));

            Session["Styles.Last"] = Request.Url.ToString();

            return RedirectToTraits(traitIds, traitNames);
        }

        private ActionResult RedirectToTraits(List<int> traitIds, List<string> traitNames)
        {
            return Redirect(TraitsUrl(traitIds, traitNames));
        }

        private string TraitsUrl(List<int> traitIds, List<string> traitNames)
        {
            if (traitIds != null && traitIds.Count > 0)
            {
                if (traitNames == null)
                {
                    traitNames = new List<string>();

                    foreach (var id in traitIds)
                    {
                        var trait = StyleService.GetTrait(id);
                        traitNames.Add(trait.Name);
                    }
                }

                traitIds.Sort();
                traitNames.Sort();

                var traitIdString = WebUtility.UrlSlug(traitIds);
                var traitNameString = WebUtility.UrlSlug(traitNames);

                return Url.Action("Index", new { traitIdString, traitNameString });
            }
            else
            {
                return Url.Action("Index");
            }
        }
    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/TeacherTrainingOrganisations/Classes.cshtml
@model Clicks.Yoga.Portal.Models.TeacherTrainingOrganisations.OrganisationClassesModel

@{
    ViewBag.Title = "Classes";
    Layout = "~/Views/Layout/Layout.cshtml";
}

@section LeftNav
{
    @if (SecurityContext.IsOwner(Model.TeacherTrainingOrganisation))
    {
        @Html.Action("Navigation", "Profiles", new { SecurityContext.CurrentProfile.Id })
    }
    else
    {
        @Html.Action("TeacherTrainingNavigation", "Search", new { organisations = false })
    }
}

@section Head {
    <meta property="og:title" content="@Model.TeacherTrainingOrganisation.Name" />
    @if (!string.IsNullOrEmpty(Model.TeacherTrainingOrganisation.Description))
    {
        <meta property="og:description" content="@Model.TeacherTrainingOrganisation.Description" />
    }
    else
    {
        <meta property="og:description" content=" " />
    }

    @if (Model.TeacherTrainingOrganisation.Image != null)
    {
        <meta property="og:image" content="@Html.ImageUrl(Model.TeacherTrainingOrganisation.Image)" />
    }
}

@Html.Partial("ActivateProfileLinkPartial", new Clicks.Yoga.Portal.Models.Shared.ActivateProfileLinkPartialModel(Model.TeacherTrainingOrganisation.Id, Model.TeacherTrainingOrganisation.EntityTypeName))

<div id="content-slider" class="content-slider">
    <div class="profile-strip content-col @(SecurityContext.IsOwner(Model.TeacherTrainingOrganisation) ? " " : "purple-strip")" id="scroll">
        <div id="page-content">
            <article id="static">
                @Html.Action("SubjectRequestsPartial", "Notifications", new { SubjectId = Model.TeacherTrainingOrganisation.Id, SubjectTypeName = Model.TeacherTrainingOrganisation.EntityTypeName })

                @Html.Action("SummaryPartial", "Reviews", new { SubjectId = Model.TeacherTrainingOrganisation.Id, SubjectType = Model.TeacherTrainingOrganisation.EntityTypeName })

                <h2 class="teacherOrganisationHeader"><span>&nbsp;</span>@Model.TeacherTrainingOrganisation.Name</h2>

                <div class="profileBanner teacherOrganisationBanner">

                    @Html.DisplayFor(m => m.TeacherTrainingOrganisation.ProfileBanner, "ProfileBanner")

                </div>

                @Html.Partial("Tabs")

                @Html.Action("ClassWeekPartial", "Activities", new { TTOEntityId = Model.EntityHandleId, Editable = SecurityContext.IsOwner(Model.TeacherTrainingOrganisation) })
                <div class="meta">
                    <p>These listings are for information only - any reference to a third party and/or its services does not indicate our endorsement, recommendation or approval, nor does it indicate any third party's endorsement, recommendation or approval of YogaClicks.</p>
                </div>
            </article>
        </div>
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/TeacherTrainingOrganisations/CoursesPartial.cshtml
@model Clicks.Yoga.Portal.Models.TeacherTrainingOrganisations.OrganisationCoursesPartialModel

@{
    var guid = Guid.NewGuid().ToString();
}

<div id="@guid">
    @foreach (var course in Model.Courses)
    {
        if (SecurityContext.CanUpdate(course))
        {
            <div class="block-section cb course-section" data-role="Course">
                <div class="header">
                    <div class="left">
                        <h2><a href="@Url.Action("Display", "TeacherTrainingCourses", new { course.Id })">@course.Name</a></h2>

                    </div>
                    <div class="right">
                        <a href="@Url.Action("Update", "TeacherTrainingCourses", new { course.Id })" class="button silver editButton">Edit this course <span>&nbsp;</span></a>

                        @if (SecurityContext.CanDelete(course))
                        {
                            <a href="javascript:void(0)" data-role="DeleteButton" data-url="@Url.Action("Delete", "TeacherTrainingCourses")" data-course-id="@course.Id" class="button silver deleteButton"><span>&nbsp;</span></a>
                        }
                    </div>
                </div>
                <hr />
                <div class="main">
                    <div class="row">
                        @if (!string.IsNullOrEmpty(course.Duration))
                        {
                            <div><strong>Teaching hours:</strong> @course.Duration</div>
                        }
                        <div>
                            @if (course.StartDate.HasValue)
                            {
                                <strong>Start:</strong>
                                @course.StartDate.Value.ToString("MMMM yyyy")
                            }
                            &nbsp;
                            @if (course.FinishDate.HasValue)
                            {
                                <strong>End:</strong>
                                @course.FinishDate.Value.ToString("MMMM yyyy")
                            }
                            <br />
                            @if (!string.IsNullOrEmpty(course.Price))
                            {
                                <strong>Price</strong> @course.Price
                            }
                        </div>
                    </div>
                    <div class="row">
                        @if (course.Teachers.Count > 0)
                        {
                            <div>
                                @if (course.Teachers.Count > 1)
                                {
                                    <strong>Teachers:</strong>
                                }

                                @if (course.Teachers.Count == 1)
                                {
                                    <strong>Teacher:</strong>
                                }

                                @{
                                var claimedTeachers = course.Teachers.Where(x => x.Teacher.OwnerId != null);
                                var stubbTeachers = course.Teachers.Where(x => x.Teacher.OwnerId == null);
                                int noOfClaimedteachers = 0;
                                }

                                @foreach (var association in claimedTeachers)
                                {
                                    if (association.Confirmed ||
                                        SecurityContext.IsOwner(course) ||
                                        SecurityContext.IsOwner(association.Teacher) ||
                                        SecurityContext.IsSuperUser())
                                    {
                                        @Html.ActionLink(association.Teacher.Name, "Display", "Teachers", new { association.Teacher.Id }, null)

                                        noOfClaimedteachers++;

                                        if (noOfClaimedteachers != claimedTeachers.Count())
                                        {
                                            <text> | </text>
                                        }
                                    }
                                }

                                @if (stubbTeachers.Count() > 0 && claimedTeachers.Count() > 0)
                                {
                                    <text> | </text>
                                }

                                @if (stubbTeachers.Any())
                                {
                                    @Html.Raw(string.Join(" | ", stubbTeachers.Select(x => x.Teacher.Name).ToList()));
                                }
                            </div>
                        }

                        @if (course.Venues.Count > 0)
                        {
                            <div>
                                @if (course.Venues.Count > 1)
                                {
                                    <strong>Venues:</strong>
                                }
                                @if (course.Venues.Count == 1)
                                {
                                    <strong>Venue:</strong>
                                }
                                @foreach (var association in course.Venues)
                                {
                                    if (association.Confirmed || SecurityContext.IsOwner(course) || SecurityContext.IsOwner(association.Venue))
                                    {
                                        @Html.ActionLink(association.Venue.Name + " ", "Display", "Venues", new { association.Venue.Id }, null)
                                    }
                                }
                            </div>
                        }
                    </div>
                    <div class="row">
                        @if (course.AccreditationBodies.Count > 0)
                        {
                            <div>
                                @if (course.AccreditationBodies.Count > 1)
                                {
                                    <strong>Accrediting / registering bodies:</strong>
                                }
                                @if (course.AccreditationBodies.Count == 1)
                                {
                                    <strong>Accrediting body:</strong>
                                }
                                @foreach (var body in course.AccreditationBodies)
                                {
                                    @Html.ActionLink(body.Name, "Display", "AccreditationBodys", new { body.Id }, null)<span>,</span>
                                }
                            </div>
                        }

                        @if (!string.IsNullOrEmpty(course.Accreditation))
                        {
                            <div><strong>Qualification:</strong> @course.Accreditation</div>
                        }

                        @if (course.Style != null)
                        {
                            <div><strong>Style:</strong> @Html.ActionLink(course.Style.Name, "Display", "Styles", new { course.Style.Id }, null)</div>
                        }
                    </div>
                    <div class="row">
                        @if (course.Website != null)
                        {
                            <div>
                                <p>
                                    <strong>Website: </strong>
                                    <a href="@course.Website.Url" target="_blank">@course.Website.Url</a>
                                </p>
                            </div>
                        }

                    </div>
                </div>

                @if (!string.IsNullOrEmpty(course.Description))
                {

                    <div class="sectionToggleHeader"><strong>Description:</strong><span class="arrow">&nbsp;</span></div>
                    <div class="sectionToggle">@Html.NewLines(course.Description)</div>
                }

                @if (!string.IsNullOrEmpty(course.PreRequisites))
                {

                    <div class="sectionToggleHeader"><strong>Pre-requisites:</strong><span class="arrow">&nbsp;</span></div>
                    <div class="sectionToggle">@Html.NewLines(course.PreRequisites)</div>
                }

                @if (!string.IsNullOrEmpty(course.Notes))
                {
                    <div class="sectionToggleHeader"><strong>Notes:</strong><span class="arrow">&nbsp;</span></div>
                    <div class="sectionToggle">@Html.NewLines(course.Notes)</div>
                }
            </div>
        }
        else
        {
            <div class="block-section cb course-section" data-role="Course">
                <h2><a href="@Url.Action("Display", "TeacherTrainingCourses", new { course.Id })">@course.Name</a></h2>
                @if (course.Finished)
                {
                    <div>
                        @Html.Action("SummaryPartial", "Reviews", new { SubjectId = course.Id, SubjectType = course.EntityTypeName })
                    </div>
                }
            </div>
        }
    }
</div>

<script>
    $(function () {
        var $container = $('#@guid');

        $container.on('click', 'a[data-role=DeleteButton]', function () {
            var $button = $(this);

            $.ajax({
                type: 'POST',
                url: $button.attr('data-url'),
                data: { Id: $button.attr('data-course-id') },
                success: function () {
                    $button.closest('[data-role=Course]').remove();

                }
            });
        });
    });
</script>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/TeacherTrainingOrganisations/ProfessionalPartial.cshtml
@model Clicks.Yoga.Portal.Models.Entities.TeacherModel

    <div class="connectionWrap">
        <span class="connection" data-teacherid="@Model.Id">
            <a href="@Url.Action("Display", "Teachers", new { id = Model.Id })">
                <div class="image">
                    @Html.Image(Model.Image, i => i.Resize(c => c.Width(128).Height(128).ScaleBoth().Crop()))
                </div>
                <span class="name">
                    <strong>@Model.Name</strong>
                </span>
                <span class="location">
                    @if (Model.Location != null)
                    {
                        @Model.Location.Name
                    }
                </span>
            </a>
        </span>
    </div>