YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Models/News/NewsGalleryPartialModel.cs
using System.Collections.Generic;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Portal.Models.Entities;

namespace Clicks.Yoga.Portal.Models.News
{
    public class NewsGalleryPartialModel
    {
        public NewsGalleryPartialModel(NewsStory story, IEnumerable<GalleryEntry> entries)
        {
            Story = new NewsStoryModel(story);
            Entries = new List<GalleryEntryModel>();
            
            foreach (var entry in entries)
            {
                Entries.Add(new GalleryEntryModel(entry));
            }
        }

        public NewsStoryModel Story { get; private set; }

        public IList<GalleryEntryModel> Entries { get; private set; }
    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Models/News/NewsInteractionPartialModel.cs
using Clicks.Yoga.Portal.Models.Entities;

namespace Clicks.Yoga.Portal.Models.News
{
    public class NewsInteractionPartialModel
    {
        public NewsInteractionPartialModel(NewsStoryModel story, string message)
        {
            Story = story;
            Message = message;
        }

        public NewsStoryModel Story { get; private set; }

        public string Message { get; private set; }
    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Models/News/NewsReviewPartialModel.cs
using Clicks.Yoga.Domain.Entities;

namespace Clicks.Yoga.Portal.Models.News
{
    public class NewsReviewPartialModel
    {
        public NewsReviewPartialModel(Review review)
        {
            Rating = review.Rating;
            Body = review.Body;
        }

        public decimal Rating { get; set; }

        public string Body { get; set; }
    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Models/News/NewsStoriesPartialModel.cs
using System.Collections.Generic;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Portal.Models.Entities;

namespace Clicks.Yoga.Portal.Models.News
{
    public class NewsStoriesPartialModel
    {
        public NewsStoriesPartialModel(IEnumerable<NewsStory> stories)
        {
            Stories = new List<NewsStoryModel>();

            foreach (var story in stories)
            {
                Stories.Add(new NewsStoryModel(story));
            }
        }

        public IList<NewsStoryModel> Stories { get; private set; }
    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Controllers/FansController.cs
using System.Web.Mvc;
using Clicks.Yoga.Context;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Domain.Services;
using Clicks.Yoga.Portal.Models.Fans;

namespace Clicks.Yoga.Portal.Controllers
{
    public class FansController : YogaController
    {
        public FansController(
            IWorkUnit workUnit,
            ISecurityContext securityContext,
            IFanService fanService,
            IEntityService entityService)
            : base(workUnit, securityContext)
        {
            FanService = fanService;
            EntityService = entityService;
        }

        private IFanService FanService { get; set; }

        private IEntityService EntityService { get; set; }

        public ActionResult ListPartial(int entityId, string entityTypeName)
        {
            var fans = FanService.GetFans(entityId, entityTypeName);
            var handle = EntityService.GetEntityHandle(entityId, entityTypeName);
            return View(new FanListPartialModel(handle, fans));
        }

        public ActionResult Button(int entityId, string entityTypeName, bool newsfeed = false)
        {
            bool isFanned = false;
            bool canFan = false;

            if (SecurityContext.Authenticated)
            {
                isFanned = FanService.IsFanned(SecurityContext.CurrentUser, entityId, entityTypeName);
                canFan = FanService.CanFan(SecurityContext.CurrentUser, entityId, entityTypeName);
            }

            var vm = new FanButtonModel(entityId, entityTypeName, isFanned, canFan);
            vm.NewsFeed = newsfeed;
            
            if (newsfeed)
            {
                vm.FanCount = FanService.GetFanCount(entityId, entityTypeName);
            }

            return View(vm);
        }

        public ActionResult Fan(int entityId, string entityTypeName, bool newsfeed = false)
        {
            if (SecurityContext.Authenticated && !SecurityContext.CurrentProfile.Professional)
            {
                FanService.Fan(SecurityContext.CurrentUser, entityId, entityTypeName);
                WorkUnit.Commit();
            }

            var vm = new FanButtonModel(entityId, entityTypeName, true, true);
            vm.NewsFeed = newsfeed;
            if (newsfeed)
            {
                vm.FanCount = FanService.GetFanCount(entityId, entityTypeName);    
            }
            
            return View("Button", vm);
        }

        public ActionResult Unfan(int entityId, string entityTypeName, bool newsfeed = false)
        {
            if (SecurityContext.Authenticated && !SecurityContext.CurrentProfile.Professional)
            {
                FanService.Unfan(SecurityContext.CurrentUser, entityId, entityTypeName);
                WorkUnit.Commit();
            }

            var vm = new FanButtonModel(entityId, entityTypeName, false, true);
            vm.NewsFeed = newsfeed;

            if (newsfeed)
            {
                vm.FanCount = FanService.GetFanCount(entityId, entityTypeName);
            }

            return View("Button", vm);
        }

        public ActionResult Confirmation(int entityId, string entityTypeName)
        {
            var entity = EntityService.GetEntity<IEntityHandle>(entityId, entityTypeName);
            return View(new FanConfirmationModel(entity));
        }
    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using Clicks.Yoga.Context;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Domain.Services;
using Clicks.Yoga.Media;
using Clicks.Yoga.Portal.Models.Editors;
using Clicks.Yoga.Portal.Models.Entities;
using Clicks.Yoga.Portal.Models.Media;

namespace Clicks.Yoga.Portal.Controllers
{
    public class MediaController : YogaController
    {
        public MediaController(
            IWorkUnit workUnit,
            ISecurityContext securityContext,
            IImageService imageService,
            IMediaService mediaService)
            : base(workUnit, securityContext)
        {
            ImageService = imageService;
            MediaService = mediaService;
        }

        private IImageService ImageService { get; set; }

        private IMediaService MediaService { get; set; }

        public ActionResult PostPartial(IEnumerable<int> ids, int? width)
        {
            if (ids == null)
            {
                return new EmptyResult();
            }

            var resources = MediaService.GetResources(ids);
            var model = new MediaPostPartialModel(resources, width);

            WorkUnit.Commit();

            return PartialView(model);
        }

        public ActionResult PreviewPartial(string uri)
        {
            if (uri == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.PreconditionFailed);
            }

            try
            {
                var resource = MediaService.ScanResource(uri);
                var model = new MediaPreviewPartialModel(resource);

                WorkUnit.Commit();

                return PartialView(model);
            }
            catch (UnsupportedMediaException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.PreconditionFailed);
            }
        }

        public ActionResult ScanImages(string uri)
        {
            if (uri == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.PreconditionFailed);
            }

            try
            {
                var resource = MediaService.ScanWebsiteImages(uri);
                var model = new ImageModel(resource.Image);

                WorkUnit.Commit();

                return PartialView("ImagePartial", model);
            }
            catch (UnsupportedMediaException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.PreconditionFailed);
            }
        }

        [HttpPost]
        [YogaAuthorize]
        public ActionResult UploadImage(ImageUploadModel model)
        {
            var type = ImageService.GetImageType(model.PostedFile.ContentType);

            if (type == null) return Json(new { Succeeded = false });

            var image = ImageService.CreateTemporaryImage(
                typeof(GalleryEntry).GetProperty("Image"),
                model.PostedFile.InputStream,
                model.PostedFile.ContentType);

            WorkUnit.Commit();

            var uri = string.Format("urn:yogaclicks:entity:Image:{0}", image.Id);

            return Content(Url.Action("PreviewPartial", new { Uri = uri }));
        }
    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Controllers/NewsController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Antlr.Runtime.Tree;
using Clicks.Yoga.Context;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Domain.Services;
using Clicks.Yoga.Portal.Models.Entities;
using Clicks.Yoga.Portal.Models.News;
using System.Configuration;

namespace Clicks.Yoga.Portal.Controllers
{
    public class NewsController : YogaController
    {
        public NewsController(
            IWorkUnit workUnit,
            ISecurityContext securityContext,
            IGalleryService galleryService,
            INewsService newsService,
            IReviewService reviewService,
            IWallService wallService,
            IEntityService entityService,
            IVideoService videoService,
            IFanService fanService)
            : base(workUnit, securityContext)
        {
            GalleryService = galleryService;
            NewsService = newsService;
            ReviewService = reviewService;
            WallService = wallService;
            EntityService = entityService;
            VideoService = videoService;
            FanService = fanService;
        }

        private IWallService WallService { get; set; }

        private IGalleryService GalleryService { get; set; }

        private INewsService NewsService { get; set; }

        private IReviewService ReviewService { get; set; }

        private IEntityService EntityService { get; set; }

        private IVideoService VideoService { get; set; }

        private IFanService FanService { get; set; }

        [YogaAuthorize]
        public ActionResult StoriesPartial(int? earliest, int? latest, int skip = 0, int take = -1)
        {
            if (take == -1) take = int.Parse(ConfigurationManager.AppSettings["Clicks.Yoga.InfiniteScroll.DefaultNumberOfNewsStories"]);
            var stories = NewsService.GetStories(SecurityContext.CurrentProfile.Id, earliest, latest, take, skip);

            return View(new NewsStoriesPartialModel(stories));
        }

        public ActionResult GalleryPartial(int storyId)
        {
            var story = NewsService.GetStory(storyId);

            if (story == null) return new EmptyResult();

            var gallery = GalleryService.GetGallery(story.Target.EntityId);
            var visible = GalleryService.GalleryVisible(gallery);

            if (visible)
            {
                var startTime = story.CreationTime.AddSeconds(-1);
                var endTime = story.ModificationTime.AddSeconds(1);

                var entries = gallery.Entries.Where(e => e.CreationTime >= startTime && e.CreationTime < endTime);

                return View(new NewsGalleryPartialModel(story, entries));
            }
            else
            {
                return new EmptyResult();
            }
        }

        public ActionResult ReviewPartial(int storyId)
        {
            var story = NewsService.GetStory(storyId);

            if (story == null || !story.EntityId.HasValue) return new EmptyResult();

            var review = ReviewService.GetReview(story.EntityId.Value);

            if (review == null) return new EmptyResult();

            return View(new NewsReviewPartialModel(review));
        }

        public ActionResult Share(int storyId)
        {
            if (!SecurityContext.HasActor) return new EmptyResult();

            var story = WallService.ShareStory(storyId);
            WorkUnit.Commit();

            return View("StoryPartial", new NewsStoryModel(story));
        }

        public ActionResult DeletePost(int postId)
        {
            WallService.DeletePost(postId);
            WorkUnit.Commit();

            return new EmptyResult();
        }

        [HttpPost]
        [YogaAuthorize]
        public ActionResult CreateVideo(string url)
        {
            Video video = null;

            try
            {
                video = VideoService.CreateVideo(url);
            }
            catch (ArgumentException)
            {
                return new HttpStatusCodeResult(HttpStatusCode.InternalServerError);
            }

            return Json(new {video.EmbedHtml, url});
        }

    }
}

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/ActivityPosted.cshtml
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel
<div class="wallPost activityPosted">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content">
        <span class="actorImage">@Html.DisplayFor(m => m.Actor)</span> posted in <span class="actorImage">@Html.DisplayFor(m => m.Target, "EntityHandleModelNoAvatar")</span>
        <p>@Html.NewLinesAndUris(Model.Text)</p>

        @Html.Action("PostPartial", "Media", new { Ids = Model.Resources.Select(r => r.Id) })

        @if (!Model.IsShared)
        {
            <div>
                @Html.Partial("ShareButtonPartial", Model)
            </div>
        }

        <div class="news-fan-container">
            @Html.Action("Button", "Fans", new { EntityId = Model.Id, entityTypeName = Model.EntityTypeName, newsfeed = true })
        </div>

        @if (!Model.IsShared)
        {
            <small>
                @* DWTIMEHERE *@
                @Html.LocalDateTime(@Model.CreationTime.ToUniversalTime().ToString("u"))

                @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
                {
                    <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
                }
            </small>
        }
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/FriendAddedEntity.cshtml
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel

<div class="wallPost friendAddedEntity @Model.Target.EntityType.DisplayName.ToLower()">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content">
        <div class="text">
            <span class="actorImage">@Html.DisplayFor(m => m.Actor)</span> added a new @Model.Target.EntityType.DisplayName.ToLower() <span class="actorImage">@Html.DisplayFor(m => m.Target, "EntityHandleModelNoAvatar")</span>.
        </div>

        <div class="news-fan-container">
            @Html.Action("Button", "Fans", new { EntityId = Model.Id, entityTypeName = Model.EntityTypeName, newsfeed = true })
        </div>

        <small>
            @* DWTIMEHERE *@
            @Html.LocalDateTime(@Model.CreationTime.ToUniversalTime().ToString("u"))

            @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
            {
                <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
            }
        </small>
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/FriendAddedPhotos.cshtml
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel

<div class="wallPost friendAddedPhotos">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content">
        @Html.Action("GalleryPartial", new { StoryId = Model.Id })

        @if (!Model.IsShared)
        {
            <br />

            <div>
                @Html.Partial("ShareButtonPartial", Model)
            </div>
        }
        
        <div class="news-fan-container">
            @Html.Action("Button", "Fans", new { EntityId = Model.Id, entityTypeName = Model.EntityTypeName, newsfeed = true })
        </div>

        @if (!Model.IsShared)
        {
            <small>
                @* DWTIMEHERE *@
                @Html.LocalDateTime(@Model.CreationTime.ToUniversalTime().ToString("u"))

                @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
                {
                    <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
                }
            </small>
        }
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/FriendAddedReview.cshtml
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel
<div class="wallPost friendAddedReview">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content">
        <div class="text">
            <span class="actorImage">@Html.DisplayFor(m => m.Actor)</span> reviewed <span class="actorImage">@Html.DisplayFor(m => m.Target, "EntityHandleModelNoAvatar")</span>.
            @Html.Action("ReviewPartial", new { StoryId = Model.Id })
        </div>

        <div class="news-fan-container">
            @Html.Action("Button", "Fans", new { EntityId = Model.Id, entityTypeName = Model.EntityTypeName, newsfeed = true })
        </div>

        <small>
            @* DWTIMEHERE *@
            @Html.LocalDateTime(@Model.CreationTime.ToUniversalTime().ToString("u"))

            @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
            {
            <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
            }
        </small>
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/FriendAttendingActivity.cshtml
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel

<div class="wallPost friendAttendingActivity">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content">
        <div class="text">
            <span class="actorImage">@Html.DisplayFor(m => m.Actor)</span> will be attending <span class="actorImage">@Html.DisplayFor(m => m.Target, "EntityHandleModelNoAvatar")</span>.
        </div>
        <div class="news-fan-container">
            @Html.Action("Button", "Fans", new { EntityId = Model.Id, entityTypeName = Model.EntityTypeName, newsfeed = true })
        </div>
        <small>
            @* DWTIMEHERE *@
            @Html.LocalDateTime(@Model.CreationTime.ToUniversalTime().ToString("u"))

            @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
            {
                <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
            }
        </small>
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/FriendFanned.cshtml
@using Clicks.Yoga.Portal.Models.News
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel

<div class="wallPost friendFanned">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content">
        <div class="text">
            <span class="actorImage">@Html.DisplayFor(m => m.Actor)</span> became a fan of <span class="actorImage">@Html.DisplayFor(m => m.Target, "EntityHandleModelNoAvatar")</span>.
        </div>
        <small>
            @* DWTIMEHERE *@
            @Html.LocalDateTime(@Model.CreationTime.ToUniversalTime().ToString("u"))

            @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
            {
                <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
            }
        </small>
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/FriendJoinedGroup.cshtml
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel
<div class="wallPost friendJoinedGroup">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content">
        <div class="text">
            <span class="actorImage">@Html.DisplayFor(m => m.Actor)</span> joined <span class="actorImage">@Html.DisplayFor(m => m.Target, "EntityHandleModelNoAvatar")</span>.
        </div>
        <div class="news-fan-container">
            @Html.Action("Button", "Fans", new { EntityId = Model.Id, entityTypeName = Model.EntityTypeName, newsfeed = true })
        </div>
        <small>
            @* DWTIMEHERE *@
            @Html.LocalDateTime(@Model.CreationTime.ToUniversalTime().ToString("u"))

            @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
            {
                <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
            }
        </small>
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/FriendMadeFriend.cshtml
@using Clicks.Yoga.Portal.Models.News
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel
<div class="wallPost friendMadeFriend">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content">
        <div class="text">
            <span class="actorImage">@Html.DisplayFor(m => m.Actor)</span> is now friends with <span class="actorImage">@Html.DisplayFor(m => m.Target, "EntityHandleModelNoAvatar")</span>.
        </div>
        <div class="news-fan-container">
            @Html.Action("Button", "Fans", new { EntityId = Model.Id, entityTypeName = Model.EntityTypeName, newsfeed = true })
        </div>
        <small>
            @* DWTIMEHERE *@
            @Html.LocalDateTime(@Model.CreationTime.ToUniversalTime().ToString("u"))

            @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
            {
                <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
            }
        </small>
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/FriendPosted.cshtml
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel

<div class="wallPost friendPosted">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content">
        <span class="actorImage">@Html.DisplayFor(m => m.Actor)</span>
        <div class="text">
            <div class="more-block readmore-js-section">
                <p>@Html.NewLinesAndUris(Model.Text)</p>
            </div>
        </div>

        @Html.Action("PostPartial", "Media", new { Ids = Model.Resources.Select(r => r.Id) })

        @if (!Model.IsShared)
        {
            <div class="news-share-button-container">
                @Html.Partial("ShareButtonPartial", Model)
            </div>
        }
        
        <div class="news-fan-container">
            @Html.Action("Button", "Fans", new { EntityId = Model.Id, entityTypeName = Model.EntityTypeName, newsfeed = true })
        </div>
        
        @if (!Model.IsShared)
        {
            <small>
                @* DWTIMEHERE *@
                @Html.LocalDateTime(Model.CreationTime.ToUniversalTime().ToString("u"))

                @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
                {
                    <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
                }
            </small>
        }
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/FriendSharedStory.cshtml
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel
@using System.Configuration
@{
        var advertiserUserId = int.Parse(ConfigurationManager.AppSettings["Clicks.Yoga.Advertiser.UserId"]);
}

<div class="wallPost friendPosted sharedStory">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content" style="border-bottom: 1px solid #e5e5e5; padding-bottom: 12px;">
        <div class="text">
            <div class="more-block readmore-js-section">
                @Html.DisplayFor(m => m.Actor) shared a post by 
                @if (Model.ShareOriginal.Actor.Id == advertiserUserId)
                {
                    <span class="news-updates-post-title">YogaClicks News & Updates</span>
                }
                else
                {
                 @Html.DisplayFor(m => m.ShareOriginal.Actor, "EntityHandleModelNoAvatar")
                }
            </div>
        </div>
    </div>
</div>

@Html.Partial(Model.ShareOriginal.ViewPath, Model.ShareOriginal)

<div class="wallPost friendPosted sharedStory">
    <div class="content">

        <div class="news-share-button-container">
            @Html.Partial("ShareButtonPartial", Model)
        </div>

        <small>
            @Model.Time

            @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
            {
                <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
            }
        </small>
    </div>
</div>

YogaClicks/UpdatedPackages-BootStrap/Clicks.Yoga.Portal/Views/News/Stories/GroupPosted.cshtml
@model Clicks.Yoga.Portal.Models.Entities.NewsStoryModel
@using System.Configuration
@{
    var newsUpdateGroupId = int.Parse(ConfigurationManager.AppSettings["Clicks.Yoga.NewsUpdateGroup.Id"]);
    var advertiserUserId = int.Parse(ConfigurationManager.AppSettings["Clicks.Yoga.Advertiser.UserId"]);
}
<div class="wallPost groupPosted">
    <div class="wallPostIcon">
        <span>&nbsp;</span>
    </div>
    <div class="content">
        <div class="text">
            @if (Model.Subject.Id == newsUpdateGroupId)
            {
                <div class="more-block readmore-js-section">
                    <div class="news-updates-post-title"><img src="~/Images/yc-square.png" style="width:60px;" />YogaClicks News & Updates</div>

                    @if (Model.Actor.Id == advertiserUserId)
                    {
                        <a href="/static/advertise-with-us" target="_blank" class="sponsored-link">Sponsored</a>
                    }
                    <p>@Html.NewLinesAndUris(Model.Text)</p>
                </div>
            }
            else
            {
                <div class="more-block readmore-js-section">
                    @Html.DisplayFor(m => m.Actor) posted in @Html.DisplayFor(m => m.Target, "EntityHandleModelNoAvatar")
                    <p>@Html.NewLinesAndUris(Model.Text)</p>
                </div>
            }
        </div>

        @Html.Action("PostPartial", "Media", new { Ids = Model.Resources.Select(r => r.Id) })




        @if (!Model.IsShared)
        {
            <div class="news-share-button-container">
                @Html.Partial("ShareButtonPartial", Model)
            </div>
        }
        
        <div class="news-fan-container">
            @Html.Action("Button", "Fans", new { EntityId = Model.Id, entityTypeName = Model.EntityTypeName, newsfeed = true })
        </div>

        @if (!Model.IsShared)
        {
            <small>
                @* DWTIMEHERE *@
                @Html.LocalDateTime(@Model.CreationTime.ToUniversalTime().ToString("u"))

                @if (Model.EntityId > 0 && SecurityContext.IsOwner(Model.Subject))
                {
                    <a href="javascript:void(0)" data-role="DeletePostButton" data-url="@Url.Action("DeletePost")" data-post-id="@Model.EntityId">Delete</a>
                }
            </small>
        }
        
    </div>
</div>