YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Models/Fans/FanButtonModel.cs
namespace Clicks.Yoga.Portal.Models.Fans
{
    public class FanButtonModel
    {
        public FanButtonModel(int entityId, string entityTypeName, bool isFanned, bool canFan  )
        {
            EntityId = entityId;
            EntityTypeName = entityTypeName;
            IsFanned = isFanned;
            CanFan = canFan;
        }

        public int EntityId { get; set; }

        public string EntityTypeName { get; set; }

        public bool IsFanned { get; set; }

        public bool CanFan { get; set; }

        public bool NewsFeed { get; set; }

        public int FanCount { get; set; }
    }
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Controllers/ReviewsController.cs
using System.Web.Mvc;
using Clicks.Yoga.Context;
using Clicks.Yoga.Domain;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Domain.Services;
using Clicks.Yoga.Portal.Models.Reviews;
using Clicks.Yoga.Portal.Models.Shared;

namespace Clicks.Yoga.Portal.Controllers
{
    [YogaAuthorize]
    public class ReviewsController : YogaController
    {
        public ReviewsController(
            IWorkUnit workUnit,
            ISecurityContext securityContext,
            IEntityService entityService,
            IReviewService reviewService,
            ITeacherService teacherService,
            IVenueService venueService)
            : base(workUnit, securityContext)
        {
            EntityService = entityService;
            ReviewService = reviewService;
            TeacherService = teacherService;
            VenueService = venueService;
        }

        private IEntityService EntityService { get; set; }

        private IReviewService ReviewService { get; set; }

        private ITeacherService TeacherService { get; set; }

        private IVenueService VenueService { get; set; }

        private IReviewable Subject { get; set; }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        [AllowAnonymous]
        public ActionResult FilterableListPartial(ReviewSearchCriteriaModel parameters)
        {
            var criteria = new ReviewSearchCriteria();
            parameters.PopulateEntity(criteria, ReviewService, EntityService);
            var experiences = ReviewService.GetReviewExperiences(criteria);
            parameters.PopulateMetadata(experiences);
            return PartialView(parameters);
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        [AllowAnonymous]
        public ActionResult ListPartial(ReviewSearchCriteriaModel parameters)
        {
            var criteria = new ReviewSearchCriteria();
            parameters.PopulateEntity(criteria, ReviewService, EntityService);
            var reviews = ReviewService.GetReviews(criteria);
            var showSubject = criteria.Author != null;
            var showChild = criteria.Parent != null;
            return PartialView("ListPartial", new ReviewListPartialModel(reviews, showSubject, showChild));
        }

        [AllowAnonymous]
        public ActionResult SummaryPartial(ReviewSearchCriteriaModel parameters)
        {
            var criteria = new ReviewSearchCriteria();
            parameters.PopulateEntity(criteria, ReviewService, EntityService);
            var statistics = ReviewService.GetStatistics(criteria);
            var subject = parameters.SubjectId.HasValue ? EntityService.GetEntity<IReviewable>(parameters.SubjectId.Value, parameters.SubjectType) : null;
            return PartialView("SummaryPartial", new ReviewSummaryPartialModel(parameters, statistics, subject));
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        [AllowAnonymous]
        public ActionResult RatingPartial(ReviewSearchCriteriaModel parameters)
        {
            var criteria = new ReviewSearchCriteria();
            parameters.PopulateEntity(criteria, ReviewService, EntityService);
            var statistics = ReviewService.GetStatistics(criteria);
            return PartialView("RatingPartial", new ReviewRatingPartialModel(statistics));
        }

        
        public ActionResult Display(int id)
        {
            var review = ReviewService.GetReviewForDisplay(id);
            return View(new ReviewDisplayModel(review));
        }

        
        [YogaAuthorize]
        public ActionResult Create(int subjectId, string subjectType, string destination)
        {
            Subject = EntityService.GetEntity<IReviewable>(subjectId, subjectType);

            if (!SecurityContext.HasActor || Subject == null) throw new PermissionDeniedException();

            var model = (ReviewCreateModel)new ReviewCreateModel(SecurityContext.CurrentActor, Subject).PopulateMetadata(ReviewService, Subject);

            model.Destination = destination;

            return View(model);
        }

        [HttpPost]
        [YogaAuthorize]
        public ActionResult Create(ReviewCreateModel model)
        {
            Subject = EntityService.GetEntity<IReviewable>(model.Subject.Id, model.Subject.EntityType.Name);

            if (!SecurityContext.HasActor || Subject == null) throw new PermissionDeniedException();

            if (!ModelState.IsValid) return View((ReviewCreateModel)model.PopulateMetadata(ReviewService, Subject));

            var review = new Review();

            review.Owner = SecurityContext.CurrentUser;
            review.AuthorHandle = EntityService.EnsureEntityHandle(SecurityContext.CurrentActor);
            review.SubjectHandle = EntityService.EnsureEntityHandle(Subject);

            model.PopulateEntity(review, ReviewService);

            ReviewService.AddReview(review);
            WorkUnit.Commit();

            return View("CloseModal", new CloseModalModel(null, "CreateReview"));
        }

        
        [YogaAuthorize]
        public ActionResult Update(int id, string destination)
        {
            var review = ReviewService.GetReviewForEditing(id);

            Subject = EntityService.GetEntity<IReviewable>(review.SubjectHandle);

            var model = (ReviewUpdateModel)new ReviewUpdateModel(review, Subject).PopulateMetadata(ReviewService, Subject);

            model.Subject.Id = id;
            model.Destination = destination;

            return View(model);
        }

        [HttpPost]
        [YogaAuthorize]
        public ActionResult Update(ReviewUpdateModel model)
        {
            var review = ReviewService.GetReviewForEditing(model.ReviewId);
            
            Subject = EntityService.GetEntity<IReviewable>(review.SubjectHandle);

            if (!ModelState.IsValid) return View((ReviewUpdateModel)model.PopulateMetadata(ReviewService, Subject));

            model.PopulateEntity(review, ReviewService);
            WorkUnit.Commit();

            return View("CloseModal");
        }

        [YogaAuthorize]
        public ActionResult Feedback(int id, bool helpful)
        {
            var review = ReviewService.GetReviewForDisplay(id);

            ReviewService.ReceiveFeedback(review, SecurityContext.CurrentUser, helpful);
            WorkUnit.Commit();

            return PartialView(new ReviewFeedbackModel(review));
        }

        public ActionResult Report(int id, string reason)
        {
            return View(new ReviewReportModel(id, reason));
        }

        [HttpPost]
        public ActionResult Report(ReviewReportModel model)
        {
            if (!ModelState.IsValid) return View(model);

            ReviewService.Report(model.ReviewId, model.Reason, model.Explanation);
            WorkUnit.Commit();

            return View("CloseModal", new CloseModalModel(null, "ReportReview"));
        }

        public ActionResult ReportPolicy()
        {
            return View();
        }
    }
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Clicks.Yoga.Context;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Domain.Services;
using Clicks.Yoga.Portal.Models.Search;
using Microsoft.Data.OData;
using Clicks.Yoga.Portal.Models.Community;
using System;
using Clicks.Yoga.Geography;
using System.Configuration;
using System.Text.RegularExpressions;
using Clicks.Yoga.Domain.Services.Interfaces;
using Clicks.Yoga.Portal.Models.Entities;

namespace Clicks.Yoga.Portal.Controllers
{
    public class SearchController : YogaController
    {
        public SearchController(
            IWorkUnit workUnit,
            ISecurityContext securityContext,
            IEntityService entityService,
            ISearchService searchService,
            IAccreditationBodyService accreditationBodyService,
            IPoseService poseService,
            IStyleService styleService,
            ITeacherTrainingService teacherTrainingService,
            ITeacherService teachers,
            IVenueService venues,
            IProfileService profileService,
            IActivityService activityService,
            IStyleOrganisationService styleOrganisationService,
             IGroupService groupService,
            IMedicService medicService
            )
            : base(workUnit, securityContext)
        {
            EntityService = entityService;
            SearchService = searchService;
            TeacherService = teachers;
            VenueService = venues;
            AccreditationBodyService = accreditationBodyService;
            PoseService = poseService;
            StyleService = styleService;
            TeacherTrainingService = teacherTrainingService;
            ProfileService = profileService;
            ActivityService = activityService;
            StyleOrganisationService = styleOrganisationService;
            GroupService = groupService;
            MedicService = medicService;
        }

        private IStyleOrganisationService StyleOrganisationService { get; set; }

        private IActivityService ActivityService { get; set; }

        private IEntityService EntityService { get; set; }

        private ISearchService SearchService { get; set; }

        private IAccreditationBodyService AccreditationBodyService { get; set; }

        private IPoseService PoseService { get; set; }

        private IStyleService StyleService { get; set; }

        private ITeacherTrainingService TeacherTrainingService { get; set; }

        private ITeacherService TeacherService { get; set; }

        private IVenueService VenueService { get; set; }

        private IProfileService ProfileService { get; set; }

        private IGroupService GroupService { get; set; }

        private IMedicService MedicService { get; set; }

        public ActionResult AutocompleteTeachers(string name, bool? owned)
        {
            if (string.IsNullOrEmpty(name) || name.Length < 3) return Json(new List<object>());

            var type = EntityService.GetEntityType("Teacher");

            var criteria = new SearchCriteria
            {
                EntityTypeIds = new[] { type.Id },
                Keywords = name,
                Owned = owned,
                Stubbed = null
            };

            SearchService.PrepareCriteria(criteria);

            var results = SearchService.Search(criteria).Results;
            var bits = results.Select(r => new { Id = r.EntityId, r.Name });

            return Json(bits, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AutocompleteVenues(string name, bool? owned)
        {
            if (string.IsNullOrEmpty(name) || name.Length < 3) return Json(new List<object>());

            var type = EntityService.GetEntityType("Venue");

            var criteria = new SearchCriteria
            {
                EntityTypeIds = new[] { type.Id },
                Keywords = name,
                Owned = owned,
                Stubbed = null
            };

            SearchService.PrepareCriteria(criteria);

            var results = SearchService.Search(criteria).Results;
            var bits = results.Select(r => new { Id = r.EntityId, r.Name });

            return Json(bits, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Index(SearchCriteriaModel criteria)
        {
            return RedirectToAction("Discover");
        }

        public ActionResult Results(SearchCriteriaModel model)
        {
            PopulateDefaultLocation(model);

            model.PageIndex = 0;
            model.PageSize = 1000;

            return View(new SearchResultsModel(model, Search(model)));
        }

        public ActionResult Discover()
        {
            return View(new SearchDiscoverModel(
                            AccreditationBodyService.LuckyDip(),
                            TeacherTrainingService.LuckyDip(),
                            TeacherService.LucyDip(),
                            VenueService.LuckyDip(),
                            StyleOrganisationService.LuckyDip(),
                            ActivityService.LuckyDip()));
        }

        public ActionResult Profiles(SearchCriteriaModel model)
        {
            PopulateDefaultLocation(model);

            model.Types = "Profile";
            return View(new SearchProfilesModel(model, Search(model)));
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult ProfilesNavigation()
        {
            return View();
        }

        public ActionResult Teachers(SearchCriteriaModel model)
        {
            PopulateDefaultLocation(model);

            model.Types = "Teacher";

            return View(new SearchTeachersModel(model, Search(model)));
        }

        public ActionResult TeachersMap(SearchCriteriaModel model)
        {
            //DW - Commented out for DYC-44 to avoid entering default
            //PopulateDefaultLocation(model);

            model.Types = "Teacher";
            model.PageSize = null;
            SetSearchCriteria(model);
            model.Stubbed = false;
            return View(new SearchTeachersModel(model));
        }

        [HttpPost]
        public ActionResult TeachersJson(SearchCriteriaModel model)
        {
            model.Types = "Teacher";
            model.PageSize = 1000;
            SetSearchCriteria(model);
            //var searchDistance = decimal.Parse(ConfigurationManager.AppSettings["Clicks.Yoga.Search.Distance"]);
            var results = new List<SearchResultModel>();

            foreach (var result in Search(model).Results)
            {
                //var inRadius = InRadius(model.Longitude.Value, model.Latitude.Value, result.LocationGeography.Longitude.Value, result.LocationGeography.Latitude.Value, searchDistance);
                if (model.Location != null)
                {
                    char[] delimiters = new[] { ',', ' ' };  // List of your delimiters

                    List<String> resultArray = new List<string>();

                    if (result.City != null)
                    {
                        resultArray = result.City.ToLower().Split(delimiters, StringSplitOptions.RemoveEmptyEntries).ToList();
                    }

                    if (result.Country != null)
                    {
                        foreach (var countryItem in result.Country.ToLower().Split(delimiters, StringSplitOptions.RemoveEmptyEntries).ToList())
                        {
                            resultArray.Add(countryItem);
                        }
                    }

                    var searchArray = model.Location.ToLower().Split(delimiters, StringSplitOptions.RemoveEmptyEntries).ToList();

                    searchArray = CheckCommonAbbr(searchArray, model.Location.ToLower());

                    var matches = resultArray.Intersect(searchArray);

                    if (matches.Any())
                    {
                        results.Add(new SearchResultModel(result));
                    }
                }
                else
                {
                    results.Add(new SearchResultModel(result));
                }

            }

            bool empty = results.Count == 0;

            return Json(new { results, empty });
        }

        private List<string> CheckCommonAbbr(List<string> searchArray, string location)
        {
            if (location.Contains("united kingdom"))
            {
                searchArray.Add("uk");
            }
            if (location.Contains("uk"))
            {
                searchArray.Add("united");
                searchArray.Add("kingdom");
            }
            if (location.Contains("united states"))
            {
                searchArray.Add("usa");
            }
            if (location.Contains("usa"))
            {
                searchArray.Add("united");
                searchArray.Add("states");
            }

            return searchArray;
        }

        public bool InRadius(double criteria_x, double criteria_y, double result_x, double result_y, decimal searchDistance)
        {
            var distance = DistanceAlgorithm.DistanceBetweenPlaces(criteria_x, criteria_y, result_x, result_y);
            return distance <= double.Parse(searchDistance.ToString());
        }

        [HttpPost]
        public ActionResult TeacherInformation(int entityId)
        {
            var venue = TeacherService.GetTeacher(entityId);
            return PartialView(new SearchTeacherInformationModel(venue));
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        public ActionResult TeachersNavigation(string action = "Teachers")
        {
            var criteria = GetSearchCriteria();
            var model = new SearchTeachersNavigationModel(action, criteria, TeacherService.GetTeacherServices(), StyleService.GetStyles(), MedicService.GetConditions(), AccreditationBodyService.GetAccreditationBodies());

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Venues/Activities.cshtml
@model Clicks.Yoga.Portal.Models.Venues.VenueActivitiesModel

@{
    ViewBag.Title = "Activities";
    Layout = "~/Views/Layout/Layout.cshtml";
}

@section LeftNav
{
    @if (SecurityContext.IsOwner(Model.Venue))
    {
        @Html.Action("Navigation", "Profiles", new { SecurityContext.CurrentProfile.Id })
    }
    else
    {
        @Html.Action("VenuesNavigation", "Search", new { Action = "Venues" })
    }
}

@section Head {
<meta property="og:title" content="@Model.Venue.Name" />
@if (!string.IsNullOrEmpty(Model.Venue.Description))
{
    <meta property="og:description" content="@Model.Venue.Description" />
}
else
{
    <meta property="og:description" content=" " />
}

@if (Model.Venue.Image != null)
{
    <meta property="og:image" content="@Html.ImageUrl(Model.Venue.Image)" />
}
}

@{
    var guid = Guid.NewGuid().ToString();
}

@Html.Partial("ActivateProfileLinkPartial", new Clicks.Yoga.Portal.Models.Shared.ActivateProfileLinkPartialModel(Model.Venue.Id, Model.Venue.EntityTypeName))


<div id="content-slider" class="content-slider">
    <div class="profile-strip content-col @(SecurityContext.IsOwner(Model.Venue) ? " " : "purple-strip")" id="scroll">
        <div id="page-content">
            <article id="static">
                @Html.Action("SubjectRequestsPartial", "Notifications", new { SubjectId = Model.Venue.Id, SubjectTypeName = Model.Venue.EntityTypeName })

                @Html.Action("SummaryPartial", "Reviews", new { SubjectId = Model.Venue.Id, SubjectType = Model.Venue.EntityTypeName })

                <h2 class="venueHeader"><span>&nbsp;</span>@Model.Venue.Name</h2>

                <div class="profileBanner venueBanner">

                    @Html.DisplayFor(m => m.Venue.ProfileBanner, "ProfileBanner")

                </div>

                @Html.Partial("Tabs")

                <h3>Activities hosting</h3>

                @Html.Action("HostingPartial", "Activities", new { VenueId = Model.Venue.Id })

                <h3>Activities created</h3>

                @Html.Action("PromotingPartial", "Activities", new { EntityId = Model.Venue.Id, Model.Venue.EntityTypeName })

                <div class="meta">
                    <p>
                        YogaClicks is not responsible for verifying the accreditation/registration information provided. Please check with the relevant accrediting/registering body for current status.
                    </p>
                    <p>These listings are for information only - any reference to a third party and/or its services does not indicate our endorsement, recommendation or approval, nor does it indicate any third party's endorsement, recommendation or approval of YogaClicks.</p>
                </div>
            </article>
        </div>
    </div>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Venues/ClaimStep1.cshtml
@using Clicks.Yoga.Portal.Models.Venues
@model Clicks.Yoga.Portal.Models.Venues.VenueClaimStep1Model

@{
    Layout = "~/Views/Layout/Modal.cshtml";
}

@using (Html.BeginForm("ClaimStep1", "Venues"))
{
    @Html.Serialize("ClaimModel", ViewBag.ClaimModel as VenueClaimModel)
    
    <h2 class="greenHeader">Claim ownership of this venue</h2>
    <hr />
    <ul class="steps steps3">
        <li class="active"><span>Step 1</span></li>
        <li><span>Step 2</span></li>
        <li><span>Step 3</span></li>
    </ul>
    <div class="activity-meta scrollableiFrame">
        @Html.ValidationSummary()
        <h3 class="cb">@Model.Name</h3>
        <div class="halfWidth">
            @Html.CheckBoxFor(m => m.Owned) I own/manage this venue
        </div>
    </div>
    <hr />
    <div>
        <a href="javascript:parent.$.fancybox.close();" class="textLink fl">Cancel</a>
        <button class="button pink large fr">Next</button>
    </div>
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Venues/Classes.cshtml
@model Clicks.Yoga.Portal.Models.Venues.VenueClassesModel

@{
    ViewBag.Title = "Classes";
    Layout = "~/Views/Layout/Layout.cshtml";
}

@section LeftNav
{
    @if (SecurityContext.IsOwner(Model.Venue))
    {
        @Html.Action("Navigation", "Profiles", new { SecurityContext.CurrentProfile.Id })
    }
    else
    {
        @Html.Action("VenuesNavigation", "Search", new { Action = "Venues" })
    }
}

@section Head {
<meta property="og:title" content="@Model.Venue.Name" />
@if (!string.IsNullOrEmpty(Model.Venue.Description))
{
    <meta property="og:description" content="@Model.Venue.Description" />
}
else
{
    <meta property="og:description" content=" " />
}

@if (Model.Venue.Image != null)
{
    <meta property="og:image" content="@Html.ImageUrl(Model.Venue.Image)" />
}
}

@Html.Partial("ActivateProfileLinkPartial", new Clicks.Yoga.Portal.Models.Shared.ActivateProfileLinkPartialModel(Model.Venue.Id, Model.Venue.EntityTypeName))

<div id="content-slider" class="content-slider">
    <div class="profile-strip content-col @(SecurityContext.IsOwner(Model.Venue) ? " " : "purple-strip")" id="scroll">
        <div id="page-content">
            <article id="static">
                @Html.Action("SubjectRequestsPartial", "Notifications", new { SubjectId = Model.Venue.Id, SubjectTypeName = Model.Venue.EntityTypeName })

                @Html.Action("SummaryPartial", "Reviews", new { SubjectId = Model.Venue.Id, SubjectType = Model.Venue.EntityTypeName })

                <h2 class="venueHeader"><span>&nbsp;</span>@Model.Venue.Name</h2>

                <div class="profileBanner venueBanner">

                    @Html.DisplayFor(m => m.Venue.ProfileBanner, "ProfileBanner")

                </div>

                @Html.Partial("Tabs")
            
            

                @Html.Action("ClassWeekPartial", "Activities", new { VenueId = Model.Venue.Id, Editable = SecurityContext.IsOwner(Model.Venue) })
                            <div class="meta">
                                <p>
                                    YogaClicks is not responsible for verifying the accreditation/registration information provided. Please check with the relevant accrediting/registering body for current status.
                                </p>
                        <p>These listings are for information only - any reference to a third party and/or its services does not indicate our endorsement, recommendation or approval, nor does it indicate any third party's endorsement, recommendation or approval of YogaClicks.</p>
                    </div>
            </article>
        </div>
    </div>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Venues/Groups.cshtml
@model Clicks.Yoga.Portal.Models.Venues.VenueGroupsModel

@{
    ViewBag.Title = "Groups";
    Layout = "~/Views/Layout/Layout.cshtml";
}

@section LeftNav
{
    @if (SecurityContext.IsOwner(Model.Venue))
    {
        @Html.Action("Navigation", "Profiles", new { SecurityContext.CurrentProfile.Id })
    }
    else
    {
        @Html.Action("VenuesNavigation", "Search", new { Action = "Venues" })
    }
}

@section Head {
<meta property="og:title" content="@Model.Venue.Name" />
@if (!string.IsNullOrEmpty(Model.Venue.Description))
{
    <meta property="og:description" content="@Model.Venue.Description" />
}
else
{
    <meta property="og:description" content=" " />
}

@if (Model.Venue.Image != null)
{
    <meta property="og:image" content="@Html.ImageUrl(Model.Venue.Image)" />
}
}

@{
    var guid = Guid.NewGuid().ToString();
}

@Html.Partial("ActivateProfileLinkPartial", new Clicks.Yoga.Portal.Models.Shared.ActivateProfileLinkPartialModel(Model.Venue.Id, Model.Venue.EntityTypeName))

<div id="content-slider" class="content-slider">
    <div class="profile-strip content-col @(SecurityContext.IsOwner(Model.Venue) ? " " : "purple-strip")" id="scroll">
        <div id="page-content">
            <article id="static">
                @Html.Action("SubjectRequestsPartial", "Notifications", new { SubjectId = Model.Venue.Id, SubjectTypeName = Model.Venue.EntityTypeName })

                @Html.Action("SummaryPartial", "Reviews", new { SubjectId = Model.Venue.Id, SubjectType = Model.Venue.EntityTypeName })

                <h2 class="venueHeader"><span>&nbsp;</span>@Model.Venue.Name</h2>

                <div class="profileBanner venueBanner">

                    @Html.DisplayFor(m => m.Venue.ProfileBanner, "ProfileBanner")

                </div>

                @Html.Partial("Tabs")

                @Html.Action("ProfessionalPartial", "Groups", new { EntityId = Model.Venue.Id, Model.Venue.EntityTypeName })

                <div class="meta">
                    <p>
                        YogaClicks is not responsible for verifying the accreditation/registration information provided. Please check with the relevant accrediting/registering body for current status.
                    </p>
                    <p>These listings are for information only - any reference to a third party and/or its services does not indicate our endorsement, recommendation or approval, nor does it indicate any third party's endorsement, recommendation or approval of YogaClicks.</p>
                </div>
            </article>
        </div>
    </div>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Venues/Schedule.cshtml
@model Clicks.Yoga.Portal.Models.Venues.VenueClassesModel

@{
    ViewBag.Title = "Classes";
    Layout = "~/Views/Layout/Layout.cshtml";
}

@section LeftNav
{
    @if (SecurityContext.IsOwner(Model.Venue))
    {
        @Html.Action("Navigation", "Profiles", new { SecurityContext.CurrentProfile.Id })
    }
    else
    {
        @Html.Action("VenuesNavigation", "Search", new { Action = "Venues" })
    }
}

@section Head {
    <meta property="og:title" content="@Model.Venue.Name" />
    @if (!string.IsNullOrEmpty(Model.Venue.Description))
    {
        <meta property="og:description" content="@Model.Venue.Description" />
    }
    else
    {
        <meta property="og:description" content=" " />
    }

    @if (Model.Venue.Image != null)
    {
        <meta property="og:image" content="@Html.ImageUrl(Model.Venue.Image)" />
    }
}

@Html.Partial("ActivateProfileLinkPartial", new Clicks.Yoga.Portal.Models.Shared.ActivateProfileLinkPartialModel(Model.Venue.Id, Model.Venue.EntityTypeName))

<div id="content-slider" class="content-slider">
    <div class="profile-strip content-col @(SecurityContext.IsOwner(Model.Venue) ? " " : "purple-strip")" id="scroll">
        <div id="page-content">
            <article id="static">
                @Html.Action("SubjectRequestsPartial", "Notifications", new { SubjectId = Model.Venue.Id, SubjectTypeName = Model.Venue.EntityTypeName })

                @Html.Action("SummaryPartial", "Reviews", new { SubjectId = Model.Venue.Id, SubjectType = Model.Venue.EntityTypeName })

                <h2 class="venueHeader"><span>&nbsp;</span>@Model.Venue.Name</h2>

                <div class="profileBanner venueBanner">

                    @Html.DisplayFor(m => m.Venue.ProfileBanner, "ProfileBanner")

                </div>

                @Html.Partial("Tabs")

                @Html.Action("ScheduleWeekPartial", "Activities", new { VenueId = Model.Venue.Id, Editable = SecurityContext.IsOwner(Model.Venue) })
                <div class="meta">
                    <p>
                        YogaClicks is not responsible for verifying the accreditation/registration information provided. Please check with the relevant accrediting/registering body for current status.
                    </p>
                    <p>These listings are for information only - any reference to a third party and/or its services does not indicate our endorsement, recommendation or approval, nor does it indicate any third party's endorsement, recommendation or approval of YogaClicks.</p>
                </div>
            </article>
        </div>
    </div>
</div>