YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Models/Shared/ActivateProfileLinkPartialModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Clicks.Yoga.Portal.Models.Shared
{
    public class ActivateProfileLinkPartialModel
    {
        public ActivateProfileLinkPartialModel(int entityId, string entityTypeName)
        {
            EntityId = entityId;
            EntityTypeName = entityTypeName;
        }

        public int EntityId { get; set; }

        public string EntityTypeName { get; set; }
    }
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Models/Shared/CloseModalModel.cs
namespace Clicks.Yoga.Portal.Models.Shared
{
    public class CloseModalModel
    {
        public CloseModalModel(string destination, string reason)
        {
            Destination = destination;
            Reason = reason;
        }

        public string Destination { get; set; }

        public string Reason { get; set; }

        public string ViewPath
        {
            get { return string.Format("~/Views/Shared/CloseModalReasons/{0}.cshtml", Reason); }
        }
    }
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Models/Shared/CommentPartialModel.cs
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Portal.Models.Entities;

namespace Clicks.Yoga.Portal.Models.Shared
{
    public class CommentPartialModel
    {
        public CommentPartialModel(EntityReference subject, Comment comment, CommentPermissions permissions)
        {
            Subject = subject;
            Comment = new CommentModel(comment);
            Permissions = permissions;
        }

        public CommentPartialModel(EntityReference subject, CommentModel comment, CommentPermissions permissions)
        {
            Subject = subject;
            Comment = comment;
            Permissions = permissions;
        }

        public EntityReference Subject { get; private set; }

        public CommentModel Comment { get; private set; }

        public CommentPermissions Permissions { get; private set; }
    }
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Models/Shared/CommentsPartialModel.cs
using System.Collections.Generic;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Portal.Models.Entities;

namespace Clicks.Yoga.Portal.Models.Shared
{
    public class CommentsPartialModel
    {
        public CommentsPartialModel(EntityReference subject, IEnumerable<CommentModel> comments, CommentPermissions permissions)
        {
            Subject = subject;
            Permissions = permissions;
            Comments = new List<CommentModel>();

            foreach (var comment in comments)
            {
                Comments.Add(comment);
            }
        }

        public CommentsPartialModel(int subjectId, string subjectTypeName, IEnumerable<CommentModel> comments, CommentPermissions permissions)
            : this(new EntityReference(subjectId, subjectTypeName), comments, permissions)
        {}

        public EntityReference Subject { get; private set; }

        public IList<CommentModel> Comments { get; private set; }

        public CommentPermissions Permissions { get; private set; }
    }
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Models/Shared/ReviewsPartialModel.cs
namespace Clicks.Yoga.Portal.Models.Shared
{
    public class ReviewsPartialModel
    {
        public string Action { get; set; }

        public int EntityId { get; set; }

        public string EntityType { get; set; }
    }
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Models/Shared/SuperUserAccessPartialModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Portal.Models.Entities;

namespace Clicks.Yoga.Portal.Models.Shared
{
    public class SuperUserAccessPartialModel
    {
        public SuperUserAccessPartialModel(int userId, User user)
        {
            UserId = userId;
            User = new UserModel(user);
        }

        public int UserId { get; set; }
        public UserModel User { get; set; }
    }
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Controllers/QuotesController.cs
using System.Web.Mvc;
using Clicks.Yoga.Context;
using Clicks.Yoga.Domain.Services;
using Clicks.Yoga.Portal.Models.Quotes;

namespace Clicks.Yoga.Portal.Controllers
{
    public class QuotesController : YogaController
    {
        public QuotesController(
            IWorkUnit workUnit,
            ISecurityContext securityContext,
            IQuoteService quoteService
        )
            : base(workUnit, securityContext)
        {
            QuoteService = quoteService;
        }

        private IQuoteService QuoteService { get; set; }

        public ActionResult Index(string author)
        {
            return View(new QuoteIndexModel(QuoteService.GetQuotes(), author));
        }

        public ActionResult Display(int id)
        {
            var quote = QuoteService.GetQuoteForDisplay(id);

            return RedirectToAction("Index", new { quote.Author });
        }
    }
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Controllers/ReviewsController.cs
using System.Web.Mvc;
using Clicks.Yoga.Context;
using Clicks.Yoga.Domain;
using Clicks.Yoga.Domain.Entities;
using Clicks.Yoga.Domain.Services;
using Clicks.Yoga.Portal.Models.Reviews;
using Clicks.Yoga.Portal.Models.Shared;

namespace Clicks.Yoga.Portal.Controllers
{
    [YogaAuthorize]
    public class ReviewsController : YogaController
    {
        public ReviewsController(
            IWorkUnit workUnit,
            ISecurityContext securityContext,
            IEntityService entityService,
            IReviewService reviewService,
            ITeacherService teacherService,
            IVenueService venueService)
            : base(workUnit, securityContext)
        {
            EntityService = entityService;
            ReviewService = reviewService;
            TeacherService = teacherService;
            VenueService = venueService;
        }

        private IEntityService EntityService { get; set; }

        private IReviewService ReviewService { get; set; }

        private ITeacherService TeacherService { get; set; }

        private IVenueService VenueService { get; set; }

        private IReviewable Subject { get; set; }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        [AllowAnonymous]
        public ActionResult FilterableListPartial(ReviewSearchCriteriaModel parameters)
        {
            var criteria = new ReviewSearchCriteria();
            parameters.PopulateEntity(criteria, ReviewService, EntityService);
            var experiences = ReviewService.GetReviewExperiences(criteria);
            parameters.PopulateMetadata(experiences);
            return PartialView(parameters);
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        [AllowAnonymous]
        public ActionResult ListPartial(ReviewSearchCriteriaModel parameters)
        {
            var criteria = new ReviewSearchCriteria();
            parameters.PopulateEntity(criteria, ReviewService, EntityService);
            var reviews = ReviewService.GetReviews(criteria);
            var showSubject = criteria.Author != null;
            var showChild = criteria.Parent != null;
            return PartialView("ListPartial", new ReviewListPartialModel(reviews, showSubject, showChild));
        }

        [AllowAnonymous]
        public ActionResult SummaryPartial(ReviewSearchCriteriaModel parameters)
        {
            var criteria = new ReviewSearchCriteria();
            parameters.PopulateEntity(criteria, ReviewService, EntityService);
            var statistics = ReviewService.GetStatistics(criteria);
            var subject = parameters.SubjectId.HasValue ? EntityService.GetEntity<IReviewable>(parameters.SubjectId.Value, parameters.SubjectType) : null;
            return PartialView("SummaryPartial", new ReviewSummaryPartialModel(parameters, statistics, subject));
        }

        [AcceptVerbs(HttpVerbs.Get | HttpVerbs.Post)]
        [AllowAnonymous]
        public ActionResult RatingPartial(ReviewSearchCriteriaModel parameters)
        {
            var criteria = new ReviewSearchCriteria();
            parameters.PopulateEntity(criteria, ReviewService, EntityService);
            var statistics = ReviewService.GetStatistics(criteria);
            return PartialView("RatingPartial", new ReviewRatingPartialModel(statistics));
        }

        
        public ActionResult Display(int id)
        {
            var review = ReviewService.GetReviewForDisplay(id);
            return View(new ReviewDisplayModel(review));
        }

        
        [YogaAuthorize]
        public ActionResult Create(int subjectId, string subjectType, string destination)
        {
            Subject = EntityService.GetEntity<IReviewable>(subjectId, subjectType);

            if (!SecurityContext.HasActor || Subject == null) throw new PermissionDeniedException();

            var model = (ReviewCreateModel)new ReviewCreateModel(SecurityContext.CurrentActor, Subject).PopulateMetadata(ReviewService, Subject);

            model.Destination = destination;

            return View(model);
        }

        [HttpPost]
        [YogaAuthorize]
        public ActionResult Create(ReviewCreateModel model)
        {
            Subject = EntityService.GetEntity<IReviewable>(model.Subject.Id, model.Subject.EntityType.Name);

            if (!SecurityContext.HasActor || Subject == null) throw new PermissionDeniedException();

            if (!ModelState.IsValid) return View((ReviewCreateModel)model.PopulateMetadata(ReviewService, Subject));

            var review = new Review();

            review.Owner = SecurityContext.CurrentUser;
            review.AuthorHandle = EntityService.EnsureEntityHandle(SecurityContext.CurrentActor);
            review.SubjectHandle = EntityService.EnsureEntityHandle(Subject);

            model.PopulateEntity(review, ReviewService);

            ReviewService.AddReview(review);
            WorkUnit.Commit();

            return View("CloseModal", new CloseModalModel(null, "CreateReview"));
        }

        
        [YogaAuthorize]
        public ActionResult Update(int id, string destination)
        {
            var review = ReviewService.GetReviewForEditing(id);

            Subject = EntityService.GetEntity<IReviewable>(review.SubjectHandle);

            var model = (ReviewUpdateModel)new ReviewUpdateModel(review, Subject).PopulateMetadata(ReviewService, Subject);

            model.Subject.Id = id;
            model.Destination = destination;

            return View(model);
        }

        [HttpPost]
        [YogaAuthorize]
        public ActionResult Update(ReviewUpdateModel model)
        {
            var review = ReviewService.GetReviewForEditing(model.ReviewId);
            
            Subject = EntityService.GetEntity<IReviewable>(review.SubjectHandle);

            if (!ModelState.IsValid) return View((ReviewUpdateModel)model.PopulateMetadata(ReviewService, Subject));

            model.PopulateEntity(review, ReviewService);
            WorkUnit.Commit();

            return View("CloseModal");
        }

        [YogaAuthorize]
        public ActionResult Feedback(int id, bool helpful)
        {
            var review = ReviewService.GetReviewForDisplay(id);

            ReviewService.ReceiveFeedback(review, SecurityContext.CurrentUser, helpful);
            WorkUnit.Commit();

            return PartialView(new ReviewFeedbackModel(review));
        }

        public ActionResult Report(int id, string reason)
        {
            return View(new ReviewReportModel(id, reason));
        }

        [HttpPost]
        public ActionResult Report(ReviewReportModel model)
        {
            if (!ModelState.IsValid) return View(model);

            ReviewService.Report(model.ReviewId, model.Reason, model.Explanation);
            WorkUnit.Commit();

            return View("CloseModal", new CloseModalModel(null, "ReportReview"));
        }

        public ActionResult ReportPolicy()
        {
            return View();
        }
    }
}

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/ActivateProfileLinkPartial.cshtml
@model Clicks.Yoga.Portal.Models.Shared.ActivateProfileLinkPartialModel

<script type="text/javascript">
    $(document).ready(function() {
        $("a.personal-profile").each(function(e) {
            if ($(this).data("type") == "@Model.EntityTypeName" && $(this).data("entityid") == "@Model.EntityId") {
                $(this).addClass("active");
            }
        });
    });
</script>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/CloseModal.cshtml
@using Newtonsoft.Json
@model Clicks.Yoga.Portal.Models.Shared.CloseModalModel

@{
    Layout = "~/Views/Layout/Modal.cshtml";
}

@{
    var destination = Model != null ? Model.Destination : null;
}

<script type="text/javascript">
    $(document).ready(function() {
        setTimeout(function() {
            if (parent.$.fancybox == null || parent.$.fancybox.current == null)
                return;
            parent.$.fancybox.current.height = 400;
            parent.$.fancybox.update();
        }, 0);
    })
</script>

<h2 class="greenHeader">Congratulations</h2>
<hr class="modalHr" />
@if (Model != null && !string.IsNullOrEmpty(Model.ViewPath))
{
    @Html.Partial(Model.ViewPath)
}
else
{
    // This is the default fall back message in the case that no specific template is available
    
    <h3 class="cb blackSubHeader">Thank you, that's all the information we need for now.</h3>
}

<br /><br /><br /><br />
<div class="fr">
    <input class="button pink fr large" type="button" value="Close" onclick="top.closeModal(@(Html.Raw(JsonConvert.SerializeObject(destination)))); return false;" />
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/CommentPartial.cshtml
@model Clicks.Yoga.Portal.Models.Shared.CommentPartialModel

<div id="comment-@Model.Comment.Id" data-role="Comment" class="comment">
    <div class="left-col fl">
        <div class="profile-pic-sml">
            <a href="@Url.Entity(Model.Comment.Actor)">
                 @Html.Image(Model.Comment.Actor.Image, "Profile.jpg", i => i.Resize(c => c.Width(50).Height(50).ScaleBoth().Crop()))
            </a>
        </div>
    </div>
    <div class="right-col fr text">
        <p><strong><a href="@Url.Entity(Model.Comment.Actor)">@Model.Comment.Actor.Name</a></strong></p>

        <p>@Html.NewLines(Model.Comment.Content)</p>

        <small>
            @* DWTIMEHERE *@
            @Html.LocalDateTime(@Model.Comment.CreationTime.ToUniversalTime().ToString("u")) | 
        
            @if (Model.Permissions.Delete || SecurityContext.IsOwner(Model.Comment))
            {
                <a href="javascript:void(0)" data-role="DeleteCommentButton" data-url="@Url.Action("Delete", "Comments")" data-comment-id="@Model.Comment.Id" data-subject-id="@Model.Subject.EntityId" data-subject-type-name="@Model.Subject.EntityTypeName">Delete reply</a>
            }
        </small>
    </div>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/FollowButton.cshtml
@model Clicks.Yoga.Portal.Models.Follow.FollowButtonModel

@if (Model.IsCurrentlyFollowing)
{
    <a href="#" class="button silver follow-btn" data-add-follow="false">Un-follow</a>
}
else
{
    <a href="#" class="button silver follow-btn" data-add-follow="true">Follow</a>
}

<script>
    $('.follow-btn').click(function (e) {
        e.preventDefault();

        var $this = $(this),
            $id = @Model.EntityId,
            $addFollow = $this.data('add-follow');

        $.ajax({
            type: 'POST',
            url: '@Url.Action("FollowButton", Model.EntityName)',
            async: true,
            data: { id: $id, addFollow: $addFollow },
            success: function (html) {
                $('.follow-button-container').html(html);
            }
        });
    });
</script>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/ReviewPartial.cshtml
@using Clicks.Yoga.Domain.Entities
@using Clicks.Yoga.Portal.Models.Shared
@model Clicks.Yoga.Portal.Models.Entities.ReviewModel

@{
    var showSubject = ViewBag.ShowSubject ?? false;
    var profileHandle = showSubject ? Model.Subject : Model.Author;
    var showChild = ViewBag.ShowChild ?? false;
    var authAndSuper = false;

    if (SecurityContext != null)
    {
        if (SecurityContext.IsSuperUser())
        {
            authAndSuper = true;
        }
    }
}

<div id="review-@Model.Id" data-role="Review" class="block-section review">
    <div class="headerRow">
        <div class="left-col fl">
            <span class="rating @Html.StarRatingClass(Model.Rating)"></span>
        </div>
        <div class="right-col fr">
            <h3>
                <!-- This is used for showing the teacher training course name when viewing reviews on the organisation page, add style inside the if -->
                @if (showChild)
                {
                    <strong><a href="@Url.Action("Display", Model.Subject.Controller, new { id = Model.Subject.EntityId })">@Model.Subject.Name</a> - </strong>
                }

                &ldquo;
                @Model.Headline
                &rdquo;

            </h3>
        </div>
    </div>
    <div class="left-col fl">

        <div class="profile-pic-sml">
            <a href="@Url.Entity(profileHandle)">
                @Html.Image(profileHandle.Image, "Profile.jpg", i => i.Resize(c => c.Width(50).Height(50).ScaleBoth().Crop()))
            </a>
        </div>
        <div class="fr">
            <p class="no-mrg">
                <b>
                    <a href="@Url.Entity(profileHandle)">
                        @profileHandle.Name
                    </a>
                </b><br />

                @if (!string.IsNullOrEmpty(profileHandle.Location))
                {
                    <span>@profileHandle.Location</span><br />
                }
                @* DWTIMEHERE *@
                <span class="date">@Html.LocalDateTime(Model.CreationTime.ToUniversalTime().ToString("u"))</span>
            </p>
        </div>
    </div>
    <div class="right-col fr text">
        <div class="more-block">
            @Html.NewLines(Model.Body)
        </div>

        <br />

        @if (Model.ReviewedExperiences.Count > 0)
        {
            <p>
                <strong>Experience(s):</strong>@(string.Join(", ", Model.ReviewedExperiences.Select(e => e.Name).ToArray()))
            </p>
        }
    </div>

    @if (SecurityContext.Authenticated)
    {
        if (!SecurityContext.IsOwner(Model))
        {
            <div class="grey-bg">
                <div class="left-col fl">
                    <small>
                        <span class="reportIconWrap">
                            <img src="/images/report-icon.gif" alt="Report" title="Report" class="reportIcon" />
                            <a href="#" class="report-review">Report this review</a>
                            <div class="review-popup">
                                <small><input type="radio" name="report-@Model.Id" value="SPAM" data-location="@Url.Action("Report", "Reviews", new { Model.Id, Reason = "SPAM" })" /><span>This review is spam</span></small>
                                <small><input type="radio" name="report-@Model.Id" value="illegal or unacceptable" data-location="@Url.Action("Report", "Reviews", new { Model.Id, Reason = "illegal or unacceptable" })" /><span>This review is illegal or unacceptable</span></small>
                                <button class="submit-report button silver" data-group="report-@Model.Id">Report the review</button>
                            </div>
                        </span>
                    </small>
                </div>
                <div class="right-col fr">
                    <small class="reviewHelpful">Did you find this review helpful? <a class="review-helpful" data-review-id="@Model.Id" href="javascript:void(0)">YES</a> <a class="review-unhelpful" data-review-id="@Model.Id" href="javascript:void(0)">NO</a></small>
                </div>
            </div>
        }

        if (SecurityContext.IsOwner(Model) || SecurityContext.IsSuperUser())
        {
            <!--
              <div class="grey-bg">
                  <div class="right-col fr">
                      <small class="reviewHelpful">
                          @if (Model.HelpfulCount > 0)
                          {
                              <text>@(Model.HelpfulCount < 0 ? 0 : Model.HelpfulCount) @(Model.HelpfulCount > 1 ? "people" : "person") found this review helpful</text>
                          }
                          <a href="javascript:void(0)" data-role="DeleteReviewButton" data-review-id="@Model.Id">Delete</a>
                      </small>
                  </div>
              </div>
              -->
            <a href="javascript:void(0)" data-role="DeleteReviewButton" data-review-id="@Model.Id" class="trashCanButton">Delete</a>
        }
    }

    @Html.Partial("CommentsPartial", new CommentsPartialModel(Model.Id, "Review", Model.Comments, new CommentPermissions { Create = true, Delete = authAndSuper }))
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/header-loggedin.cshtml
 	<header role="persistent" class="clearfix">
		<h1><a href="/">
         <img src="/images/global/logo.png" alt="YogaClicks. Find it. Love it. Live it." /></a></h1>
	</header>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/left-nav-accreditingbody-search.cshtml
@model Clicks.Yoga.Portal.Models.Search.SearchAccreditingBodiesModel

<div id="navwrap">
    @Html.Partial("left-nav-menu")
    <section class="filters" id="filter-results" class="set-height">
    </section>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/left-nav-discover.cshtml
@model Clicks.Yoga.Portal.Models.Search.SearchDiscoverModel

<div id="navwrap">
    @Html.Partial("left-nav-menu")
    <section class="filters discoveryFilters" id="filter-results">
        <div class="the-sub-menu">
            <h2>Lucky Dip</h2>
            <p>No need to stay up all night to get lucky. 
                <br />
                <br />
                Explore all paths to cosmic bliss right here.</p>
        </div>
    </section>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/left-nav-quotes.cshtml
@model Clicks.Yoga.Portal.Models.Quotes.QuoteIndexModel

<div id="navwrap">
    @Html.Partial("left-nav-menu")
    <section class="filters" id="filter-results">
        <div id="filter-wrap">
            <div class="the-sub-menu">
                <h1 class="pageTitle">Quotes</h1>
                <p>Soak up the wisdom of Guruji Seinfeld, Sri Sri W. Allen, Yogacharya Einstein, Sri Devi Oprah & co</p>
                <nav class="filter">
                    @foreach (var author in Model.Authors)
                    {
                        <a href="#" class="quote-author" data-author="@author">@author (@Model.Quotes[author].Count)</a>
                    }
                </nav>
            </div>
        </div>
    </section>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/left-nav-review.cshtml
@model Clicks.Yoga.Portal.Models.Reviews.ReviewCreateModel
<div id="navwrap">
    @Html.Partial("left-nav-menu")
    <section class="filters" id="filter-results">
        <div id="filter-wrap">
            <div class="the-sub-menu">
				<h2>@Model.Subject.Name</h2>
			    <div class="profile-pic">
			        @Html.Image(Model.Subject.Image, i => i.Resize(c => c.Width(173).Height(194)))
			    </div>
			    <div style="clear: both"></div>
			</div>
		</div>
	</section>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/left-nav-static-footer.cshtml
<div id="navwrap">
    @Html.Partial("left-nav-menu")
    <section class="filters" id="filter-results">
        <div id="filter-wrap">
            <div class="the-sub-menu">
                <nav class="filter">
                    <h3>Quick links</h3>
			        <a href="@Url.Action("our-story", "static")">Our story</a>
                    <a href="@Url.Action("manifesto", "static")">Manifesto</a>
			        <a href="@Url.Action("privacy-policy", "static")">Privacy</a>
			        <a href="@Url.Action("terms-of-use", "static")">Terms of use</a>
                </nav>
            </div>
        </div>
    </section>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/left-nav-static-how-to-use.cshtml
<div id="navwrap">
    @Html.Partial("left-nav-menu")
    <section class="filters" id="filter-results">
        <div id="filter-wrap">
            <div class="the-sub-menu">
                <nav class="filter">
                    <h3>Quick Links</h3>
                    <a href="@Url.Action("Index", "Quotes")">Quotes</a>
                    <a href="@Url.Action("Index", "Glossary")">Lingo</a>                    
                    <a href="@Url.Action("beginners-faq", "static")">Beginners FAQ</a>
                    <a href="@Url.Action("is-yoga-a-religion", "static")">Is yoga a religion?</a>
                    <a href="@Url.Action("history-of-yoga", "static")">History of yoga</a>
                    <a href="@Url.Action("what-is-yoga", "static")">What is yoga?</a>
                </nav>
            </div>
        </div>
    </section>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/left-nav-static-wisdom.cshtml
<div id="navwrap">
    @Html.Partial("left-nav-menu")
    <section class="filters" id="filter-results">
        <div id="filter-wrap">
            <div class="the-sub-menu">

                    <!--<h3>Quick Links</h3>
                    <a href="@Url.Action("Index", "Quotes")">Quotes</a>
                    <a href="@Url.Action("Index", "Glossary")">Lingo</a>                    
                    <a href="@Url.Action("beginners-faq", "static")">Beginners FAQ</a>
                    <a href="@Url.Action("is-yoga-a-religion", "static")">Is yoga a religion?</a>
                    <a href="@Url.Action("history-of-yoga", "static")">History of yoga</a>
                    <a href="@Url.Action("what-is-yoga", "static")">What is yoga?</a>-->
                    <h1>Page name goes here</h1>
                    <p>Note to Lucy this needs to be updated by PT.</p>
            </div>
        </div>
    </section>
</div>

YogaClicks/Branch_YogaMeds/Clicks.Yoga.Portal/Views/Shared/my-true-self.cshtml
@model Clicks.Yoga.Portal.Models.Entities.ProfileModel

@if (Model.ProfileAnswers != null && Model.ProfileAnswers.Count > 0)
{
    <h4>My true Self...</h4>
    foreach (var answer in Model.ProfileAnswers)
    {
        <div>
            <span><strong>@answer.Question.Text</strong></span>
            <span>@answer.Text</span>
        </div>
    }
}